apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090   # L'URL de Prometheus depuis le conteneur Grafana
    isDefault: true
    editable: true